110 Incompatible Modules
drutiny/content pull request #8
Opened 2018-09-28 17:39 UTC by shanefjordan

This is to resolve the Drutiny-cs-adaptor issue #110.

2018-09-28 19:22 UTC, briantully commented
Awesome work, Shane! These new policies will be extremely helpful :)

In terms of process, do we need to squash recaptcha (79733dc & 2362c85) and varnish (652b2c5 & fdc8164)?

2018-09-30 23:00 UTC, fiasco requested changes
This is an awesome PR - thanks for pulling it together @shanefjordan! I have two key requests for change:

1. Where its an Acquia specific policy, make the namespace an Acquia one so it semantically makes more sense.
2. Add a depends declaration to the policies so that the policies omit if they pass. This will reduce the noise in a report and only raise the policy when its an issue.

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/apcDisabled.policy.yml
> +  Alternative PHP cache is not recommended on Acquia Cloud. It stores
Unless this is an Acquia specific policy, it shouldn't have references to Acquia Cloud as its an open source policy.

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/autoSlaveDisabled.policy.yml
> +  The Acquia Cloud platform is configured to auto-detect the primary and
Another reference to Acquia Cloud

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/civiCRMDisabled.policy.yml
> +  on the Acquia Cloud platform. It is   recommended to disable and
Another reference to Acquia Cloud

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/configMgmtDisabled.policy.yml
> +  same time by Git; this is not currently possible on Acquia Cloud. It is
Another reference to Acquia Cloud

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/fbconnect.policy.yml
> +name: Drupal-7:fbconnectDisabled
see https://drutiny.github.io/2.3.x/policy/#depends

You could configure this policy to omit itself if the module isn't enabled:

```
depends:
  - expression: drupal_module_enabled('fbconnect')
    on_fail: omit
```

This way it reduces the "noise" of contextual policies.

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/fileCacheDisabled.policy.yml
> +name: Drupal-7:fileCacheDisabled
Since this policy is gluster specific it should have Gluster in the name.

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/memcacheStorageDisabled.policy.yml
> +  Although not incompatible, Acquia discourages using this module’s due
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/purgeDisabled.policy.yml
> +  It is specifically intended for use on Acquia Cloud. Over time, these
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/serialDisabled.policy.yml
> +  Serial is based on an auto_increment of 1. Acquia Cloud uses an
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/shibAuthDisabled.policy.yml
> +  Shibboleth is not supported on Acquia Cloud. Other methods of achieving this
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-7/varnishModuleDisabled.policy.yml
> +  that is already available to Acquia Cloud applications. It will not work
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/apacheSolrFileDisabled.policy.yml
> +  Customers are unable to modify the solrconfig.xml file on Acquia Cloud.
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/apcDisabled.policy.yml
> +  Alternative PHP cache is not recommended on Acquia Cloud. It stores
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/memcacheStorageDisabled.policy.yml
> +  Although not incompatible, Acquia discourages using this module’s due
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/serialDisabled.policy.yml
> +  Serial is based on an auto_increment of 1. Acquia Cloud uses an
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/shibAuthDisabled.policy.yml
> +  Shibboleth is not supported on Acquia Cloud. Other methods of achieving this
Reference to Acquia. Should perhaps be an Acquia specific policy?

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/smartIPDisabled.policy.yml
> +class: \Drutiny\Plugin\Drupal8\Audit\ModuleDisabled
another policy that could be omitted if the module doesn't exist: https://drutiny.github.io/2.3.x/policy/#depends

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/supercookieDisabled.policy.yml
> +class: \Drutiny\Plugin\Drupal8\Audit\ModuleDisabled
another policy that could be omitted if the module doesn't exist: https://drutiny.github.io/2.3.x/policy/#depends

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/tbMegaMenuDisabled.policy.yml
> +name: Drupal-8:tbMegaMenuDisabled
another policy that could be omitted if the module doesn't exist: https://drutiny.github.io/2.3.x/policy/#depends

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/textSizeDisabled.policy.yml
> +name: Drupal-8:textSizeDisabled
another policy that could be omitted if the module doesn't exist: https://drutiny.github.io/2.3.x/policy/#depends

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/varnishModuleDisabled.policy.yml
> +  with Acquia Cloud applications because it requires connections to the
Acquia specific policy?
another policy that could be omitted if the module doesn't exist: https://drutiny.github.io/2.3.x/policy/#depends

2018-09-30 23:00 UTC, fiasco commented on Policy/drupal-8/viewsFilterHarmonizerDisabled.policy.yml
> +name: Drupal-8:viewsFilterHarmonizerDisabled
another policy that could be omitted if the module doesn't exist: https://drutiny.github.io/2.3.x/policy/#depends

2018-10-01 12:50 UTC, shanefjordan commented
I've cleaned up the policies that would be more dependent on Acquia hosting. I've also added the depend statements to the policies to keep reporting clean.

2018-10-01 17:55 UTC, shanefjordan commented
@fiasco The checks that are related to Acquia Cloud, should I move them to the cs-adaptor project? If so, I believe I'll have to separate them into subfolders for drupal-8 and drupal-7 since the names are the same. 

I wanted to check before making the changes and having to move everything again.

2018-10-01 20:53 UTC, fiasco commented
No, there are acquia policies in this repository, they just need to have Acquia in the name of them since they are realm specific.

2018-10-02 12:36 UTC, shanefjordan commented
@fiasco Everything should be sorted into the proper locations now and ready for review.

2018-10-02 21:40 UTC, fiasco approved these changes

2018-10-02 21:41 UTC, merged

2018-10-02 21:41 UTC, fiasco commented
Thanks Shane, this is awesome!